services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    
  redis:
    image: redis:7-alpine
    volumes:
      - ./todo-backend/redis_data:/data
      
  server:
    image: todo-backend-prod 
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
      - NODE_ENV=production 
    depends_on:
      - mongo
      - redis
    restart: unless-stopped 

  app:
    image: todo-frontend-prod 
    restart: unless-stopped

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - 80:80 
    depends_on:
      - app
      - server
    restart: unless-stopped